[build]
command = "react-router build"
publish = "build/client"

[dev]
command = "react-router dev"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/dashboard*"
    [headers.values]
    Access-Control-Allow-Origin = "*"